### ISSUE TITLE
Add confirmation field for IMEI

### ISSUE THREAD

**Issue by williamq** [mozilla/feedthefox#104]
Since the IMEI is a long number it's important we add a "Confirm IMEI" field so that users input their IMEI a second time so that we minimise typos: http://cl.ly/image/270v2b2A2147

**Comment by comzeradd** [comment]
Since this is not a password field and the number entered is visible to the user, I don't see the reason for a confirmation field. This will add more frustration than convenience. Think about when you enter the 16-digit number of your credit card. There is no confirmation.

**Comment by geroter** [comment]
True, except that with a credit card it verifies immediately that you entered the correct number by trying to process the transaction -- if you messed up, then it gives you back an error instantaneously.

I don't think that we have that immediate feedback mechanism with IMEI, do we?

**Comment by ppapadeas** [comment]
Yes we can do Imei confirmation. Closing this in favor of #89

**Comment by ppapadeas** [comment]
Validation is on issue number #81
