### ISSUE TITLE
CSP for GA

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/feedthefox#115]
Loading the website we get Content Security Policy: The page's settings blocked the loading of a resource at https://www.google-analytics.com/analytics.js ("script-src https://firefoxos.mozilla.community 'unsafe-inline' 
                 http://_.mozilla.org https://_.mozilla.org http://_.mozilla.net https://_.mozilla.net https://login.persona.org https://d1jou7z3786ary.cloudfront.net").

**Comment by johngian** [comment]
Fixed after configuration changes.
