### ISSUE TITLE
Tabzilla rendering issue

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/feedthefox#118]
The tabzilla icon is not rendered correctly when the user is not logged in.
![screen shot 2015-11-10 at 17 56 43](https://cloud.githubusercontent.com/assets/900565/11067257/702f74a8-87d4-11e5-8da0-38d18f567d34.png)

**Comment by ppapadeas** [comment]
What was the resolution used for producing this?

**Comment by akatsoulas** [comment]
947x830
