### ISSUE TITLE
Updated Device Images

### ISSUE THREAD

**Issue by brianking** [mozilla/feedthefox#126]
Requirements:
1. New, decent quality, image for each device 
2. 500x500px or greater
3. Transparent bg
4. Superimpose generic FxOS screen on them

**Comment by elioqoshi** [comment]
scratch 500px or greater, some are not at all available in that resolution. 300px is enough really, as you will be using them in Galleries mostly (a bit bigger than Thumbnails)

**Comment by elioqoshi** [comment]
Hey all,

Here are the updated images in 500px height resolution (apart the Xperia Mini which I couldn't find in a better resolution)
https://dl.dropboxusercontent.com/u/62482708/Firefox%20OS%20Participation%20Hub.zip

Inside is also a new logo for the website, using our proper fonts for the wordmark, please use that.
![website logo](https://cloud.githubusercontent.com/assets/5436686/11087598/fa87ce70-885b-11e5-94c0-3a3dbff5c5fc.png)

**Comment by williamq** [comment]
Done. 

Elio, you're a superstar. Thank you!!!

**Comment by elioqoshi** [comment]
Welcome @williamq ! :)

A note: The images before were way too big, making the page load slower. It's better now, but if we will be using the images in the same way we do right now (only thumbnails, not a full view or similar) I'd make them even more smaller (250px height or so) to speed up loading times. Would that make sense?

P.S: Maybe update the logo also :)

**Comment by brianking** [comment]
I wonder if the higher res image is needed for the device page?

e.g. https://firefoxos.mozilla.community/device/ZTE/Open

**Comment by brianking** [comment]
@comzeradd @ppapadeas do the device image urls need to be updated in the spreadsheet?

**Comment by elioqoshi** [comment]
Not really @brianking . It's pretty small there too. Although I think we can make them bigger there without losing quality (even under the 300px height)

**Comment by comzeradd** [comment]
Nice Elio! 

I converted all images to interlaced, which gives the feeling that they load faster. I also cropped the empty space around and we can use the 400px height rule for all device images. I'll adjust the device detail page to take advantage of these higher res images.

I'll update the logo too, but this needs code changes.

**Comment by elioqoshi** [comment]
Let's raise the height of the images on the single device pages to 300px and also align the images to the middle of their box like this (only bigger of course)

![device position](https://cloud.githubusercontent.com/assets/5436686/11088219/c062b930-8860-11e5-91d1-b3e409c56ddd.jpg)

**Comment by elioqoshi** [comment]
Oh commented before reading @comzeradd 's comment. Great Nikos! Awaiting the changes and will check back in :)

**Comment by comzeradd** [comment]
This is fixed at 9a3d155cb2da8d2ac71babf0bf8b2744a993b5e6 and live in production.
