### ISSUE TITLE
Replace link https://wiki.mozilla.org/Contribute/Coding/FilingGoodBugs

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla/feedthefox#127]
https://wiki.mozilla.org/Contribute/Coding/FilingGoodBugs should link to a better, more descriptive document about Filing Bugs on MDN, like: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines

Or better yet, we should create a page that is specific to Firefox OS.

**Comment by brianking** [comment]
Thoughts @mhoye ?

The context is this page: https://firefoxos.mozilla.community/b2gdroid/

**Comment by ioana-chiorean** [comment]
I really think we need to give more specific links as proposed - directly to Firefox OS - as most projects differ (at least a bit) and will be easier for new people to have specific info.

**Comment by nhirata** [comment]
I agree with ioana-chiorean.  There's so much to B2G that it might be best to try to clean up and condense things as well as point to specific documentation of how to for newer people.  I would think it would be hard to just point to one specific thing.

Also having a mozilla owned forum would be nice.

**Comment by mozillamarcia** [comment]
I will own creating this page.

**Comment by ioana-chiorean** [comment]
Thanks @mozillamarcia ! Ping me if you need help on it.

**Comment by mozillamarcia** [comment]
For B2G Droid bugs, from Fabrice - 
- We don't ship bzlite on b2gdroid, maybe we should?
- It's important that people specify which device they use and if possible which android version.
- We also don't support "shake to get logs" yet.

**Comment by mozillamarcia** [comment]
A few people already worked on https://developer.mozilla.org/en-US/Firefox_OS/Developing_Firefox_OS/Filing_bugs_against_Firefox_OS - we should use that as a good starting point.

**Comment by brianking** [comment]
@mozillamarcia @ioana-chiorean let me know what specific pages you want changes, and what links you would like removed / added. Then I will make the changes.

**Comment by ioana-chiorean** [comment]
This decision can be made by @mozillamarcia and i can help implement it.

**Comment by brianking** [comment]
Since we are removing FxOS features, this is no longer relevant. Reopen if you think it still is.
