### ISSUE TITLE
Contribute Section should have a link to FxOS Testing/Quality Assurance

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla/feedthefox#128]
We should link to FxOS QA from the top level menu, and point to https://quality.mozilla.org/teams/firefox-os-qa/.

**Comment by brianking** [comment]
It would be even better to have a dedicated QA page like the others. @mozillamarcia interested in making the copy/content for that?

**Comment by mozillamarcia** [comment]
I can create a page, but basically all the content we would want to get involved is on the QMO page which has just been overhauled.

**Comment by comzeradd** [comment]
We could have a page with just the basic information (2-3 paragraphs), that links to QMO. I would prefer we don't have mixed links on the top navbar (both internal/external links).

**Comment by ioana-chiorean** [comment]
@mozillamarcia did you start working on this? Let me know if you need help.

**Comment by brianking** [comment]
20151202 Triage - P2.

**Comment by brianking** [comment]
Since we are removing FxOS features, this is no longer relevant. Reopen if you think it still is.
