### ISSUE TITLE
ZTE Open C page is pointing to the wrong builds

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/feedthefox#129]
Open C and Open are two different devices, telling people to flash a wrong build on their device won’t end well ;)

https://firefoxos.mozilla.community/device/ZTE/Open%20C should link to http://builds.firefoxos.mozfr.org -> This is listing Open _C_ builds with documentation (English and French). All branches are available (from 2.0 to master)

https://firefoxos.mozilla.community/device/ZTE/Open should be created and link to http://mexmod.com/download_open.html

**Comment by brianking** [comment]
For now I have just changed the existing one to Open.

TODO: Add the Open C device.

**Comment by comzeradd** [comment]
Closing this in favor of #138
