### ISSUE TITLE
Main Page Logo

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/feedthefox#130]
I think the Firefox logo on the main page looks a bit out of place, as it's not either visually related to "Participation Hub" neither to the big "Firefox OS" wordmark underneath:
![issue](https://cloud.githubusercontent.com/assets/5436686/11088040/8196bd24-885f-11e5-9980-4ca5d8042d4c.jpg)

I'd suggest a change like this to make it more consisent (same goes for the inner pages):
![main page](https://cloud.githubusercontent.com/assets/5436686/11088042/850cd3a8-885f-11e5-8bcf-72246cb35f1f.jpg)

You can find the required logo file here:
![website logo](https://cloud.githubusercontent.com/assets/5436686/11088046/8833a516-885f-11e5-8231-46e0e1b4de52.png)

**Comment by comzeradd** [comment]
@elioqoshi do you by any chance have this in vector format?

**Comment by elioqoshi** [comment]
@comzeradd here:
https://dl.dropboxusercontent.com/u/62482708/Website.eps

**Comment by comzeradd** [comment]
Logo updated. It will go live on next production push.
