### ISSUE TITLE
Update Buttons Look & Feel

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/feedthefox#131]
Could we get the buttons on the website look like our classic website buttons? 
Like here the activated "Get Phone" button:
https://www.mozilla.org/en-US/firefox/os/devices/#alcatel_onetouchfire

![buttons](https://cloud.githubusercontent.com/assets/5436686/11088347/d83bf7a0-8861-11e5-879f-21ffb1b2e0f5.jpg)

**Comment by ppapadeas** [comment]
@elioqoshi it seems like a good suggestion, but I am not sure it is OK with our current design guidelines. @comzeradd thoughts?

**Comment by elioqoshi** [comment]
Which are our current design guidelines @ppapadeas ?

**Comment by comzeradd** [comment]
We are using a bootstrap theme, and this would require to override css for all button types. I don't think there is a Mozilla wide style guide, and although we try to stay as close as possible to other main websites, there is no golden rule.

Regarding the buttons, personally I prefer a flat design approach.

**Comment by elioqoshi** [comment]
Well, what we currently have does not feel at all like Mozilla honestly. If we need to go with something flat I'd suggest this:

![flat button](https://cloud.githubusercontent.com/assets/5436686/11119166/e6204268-8947-11e5-9af1-76fd3cdd8cf3.jpg)

**Comment by comzeradd** [comment]
That indeed looks better. I'll make some tests and get back.

**Comment by elioqoshi** [comment]
@comzeradd any updates on this?

**Comment by comzeradd** [comment]
Not yet. At least not from my side in terms of code. The buttons flat UI you proposed on the last comment indeed seem nicer and eventually this is the to go. I marked this as an "Easyfix" in case someone beats me to it ;)

**Comment by elioqoshi** [comment]
Great! Yeah, they should be good to go :)

**Comment by elioqoshi** [comment]
@comzeradd I haven't seen the new buttons yet online

**Comment by comzeradd** [comment]
Yes, I think this is not yet deployed /cc @johngian

**Comment by elioqoshi** [comment]
This is still not updated. Can we please wrap this up? @johngian @comzeradd
