### ISSUE TITLE
Foxfooding community builds for Flame 

### ISSUE THREAD

**Issue by nukeador** [mozilla/feedthefox#133]
Hello,

There are some community builds for Flame here:

http://www.codingfree.com/firefox-os-builds

They are using the foxfooding channel and maintained by @codingfree

**Comment by brianking** [comment]
@codingfree please confirm that they are using the foxfooding channel and are submitting telemetry data.

**Comment by brianking** [comment]
This build has been added to the spreadsheet.

@ppapadeas please update the Hub or let me know if I need to.

**Comment by gaby2300** [comment]
@brianking could you please tell me which it the Flame's foxfooding channel I should set and also what is the spreadsheet you are mentioning? I would greatly appreciate it!

**Comment by ppapadeas** [comment]
@brianking Please provide proper images for the new device added.

This is blocked by #200

**Comment by ppapadeas** [comment]
This is now added.
