### ISSUE TITLE
Change notifications/connected e-mail address in Hub profile

### ISSUE THREAD

**Issue by flaki** [mozilla/feedthefox#134]
Slightly related to #54, I've first registered with GitHub which set my Participation Hub profile e-mail to my primary GitHub e-mail. Afterwards, I signed in with Persona and have been linked to the same profile (with the same GitHub-primary e-mail), and I have no way to change my e-mail address to the ones I actually use with my daily Mozilla activities (e.g. Mozilla/Reps/etc. mails or Bugzilla).

A selector should be available on the Hub to set a default e-mail address from the list returned by Persona/GitHub.

**Comment by akatsoulas** [comment]
Right now the Hub sets as primary email the one in mozillians.org. If this suffices, I suggest to close this issue. @flaki thoughts?

**Comment by flaki** [comment]
If I get this right, there has been a change to reflect the above behavior @akatsoulas (as it didn't work like that before). Now this does seem to use the Mozillians.org default e-mail account, which is good enough for me, yes!
Thank you!

**Comment by akatsoulas** [comment]
Closing this after the last comment. Thanks @flaki!

Fixed via #164, #187.
