### ISSUE TITLE
Add builds for ZTE Open C

### ISSUE THREAD

**Issue by CronosRv** [mozilla/feedthefox#138]
Hello, community builds for zte open c here:

https://vegnuxmod.wordpress.com/openc-zte-open-c/

**Comment by TheoChevalier** [comment]
Hi,

For Open C, I think we want to list those builds http://builds.firefoxos.mozfr.org as OTA updates are enabled, all branches are available with all locales and keyboards, special Foxfooding builds are available, and the builds are tested by many people. 

Issue #129 is tracking this work.

**Comment by ppapadeas** [comment]
@brianking should we add those? please update the builds sheet so we can add them.

**Comment by dattaz** [comment]
I think we should point to mozfr build, because it's done by a mozilla community and it's more up to date. ;)

**Comment by chickenkiller** [comment]
+1 for http://builds.firefoxos.mozfr.org

**Comment by brianking** [comment]
I have added both the vegnuxmod and mozfr builds to the spreadsheet.

@ppapadeas please add to Hub or let me know if I should.

**Comment by ppapadeas** [comment]
This is now added.
