### ISSUE TITLE
Replace image for ZTE Open

### ISSUE THREAD

**Issue by elninosi** [mozilla/feedthefox#140]
Picture in https://firefoxos.mozilla.community/device/ZTE/Open is showing ZTE Open C device and not ZTE Open. 

This is the right picture of device:
![zte-open-orange-white-20130129 1](https://cloud.githubusercontent.com/assets/11082452/11096166/f4bd1418-8898-11e5-9e3d-7fc52f5fc1af.jpg)

This might confuse the user and he can potentially brick his phone with wrong build.

**Comment by brianking** [comment]
@elioqoshi can you look into that?

**Comment by elioqoshi** [comment]
Thanks Nino! I need a frontal picture of the phone, so this is not suitable but I will find one and report back :)

**Comment by elioqoshi** [comment]
@brianking @williamq here we go, please go ahead and replace it:

![open](https://cloud.githubusercontent.com/assets/5436686/11115911/f871bfdc-892e-11e5-9ded-050d5235dbe8.png)

**Comment by ppapadeas** [comment]
Done!

https://firefoxos.mozilla.community/device/ZTE/Open
