### ISSUE TITLE
"Ways to get Involved" link only points to Porting Page

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla/feedthefox#142]
https://firefoxos.mozilla.community/porting/

This is linked from the About Section of the Main Page - https://firefoxos.mozilla.community/. It seems it should point to the other activities as well, such as Foxfooding and B2G Droid.

**Comment by geroter** [comment]
Since we don't have an index page for contribute we chose this page...not
sure having an index page is necessary.

Let's watch bounces off this page in the analytics and make a data driven
decision.

**Comment by brianking** [comment]
@ppapadeas did discuss putting a widget on all the contribution pages that links to other contribution pages, to mitigate this a little bit.

**Comment by mozillamarcia** [comment]
To me, having a Ways to Get involved link encompasses a broad set of activities related to Firefox OS, including things like l10n (which is not mentioned on the site) and QA.

I am not sure this link is even needed at all if it isn't going to link to an index page.

**Comment by ppapadeas** [comment]
We will not have an index page but rather a list of all flatpages on other flatpages.

Closing this in favor of #122
