### ISSUE TITLE
Show "code name" on Devices pages

### ISSUE THREAD

**Issue by alex-mayorga** [mozilla/feedthefox#144]
It might be good idea to tell people the "code name" of their device at https://firefoxos.mozilla.community/devices/ because they're most likely going to need that bit of information once they click the big green buttons.

The ones I know of so far FWIW:

```
Xperia Z3 (leo)
Xperia Z3 Compact (aries)
Xperia Z2 (sirius)
Xperia T2 Ultra (tianchi)
Xperia E3 (flamingo)
```

**Comment by MichaelKohler** [comment]
To complete Alex' list, here are all the codenames for the mentioned Sony devices:

amami (Z1C)
aries (Z3C)
flamingo (E3)
honami (Z1)
leo (Z3)
tianchi (T2 Ultra)
sirius (Z2)

**Comment by ppapadeas** [comment]
@brianking how do you feel about this?

Probably to be displayed as part of the comment section on single device view?

**Comment by brianking** [comment]
I think these should be shown in the device name. As such, I have updated the spreadheet.

@ppapadeas please update the Hub or let me know if I should.

**Comment by brianking** [comment]
To be clear, I think the code names should also be added to the names on the Devices page.

https://firefoxos.mozilla.community/devices/?manufacturer=Sony
