### ISSUE TITLE
Text spacing issues on https://firefoxos.mozilla.community/fxos-tv/

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla/feedthefox#146]
See attached screenshot - the first link "Read the documentation to get started."

![screen shot 2015-11-11 at 2 29 17 pm](https://cloud.githubusercontent.com/assets/2171777/11104977/e8562ab0-8880-11e5-836d-0b9ac36656a2.png)

**Comment by comzeradd** [comment]
Thanks. Fixed.
