### ISSUE TITLE
Unable to file bugs on B2GDroid category

### ISSUE THREAD

**Issue by khalid32** [mozilla/feedthefox#147]
Recently I was exploring on "Firefox OS 2.5 Developer Preview" and found a bug. I was going to report it on Bugzilla in 'B2GDroid' category(Since 'B2GDroid' is the codename for this experiment). But when I press 'Submit Bug', it shows a message saying, "You must select/enter a OS".
![b2gdroid category](https://cloud.githubusercontent.com/assets/8571179/11113025/421374f0-8943-11e5-8a17-a3a0131c2911.png)

So at this moment, I'm unable to file bugs on 'B2GDroid'.

**Comment by ppapadeas** [comment]
This issue is not to be reported here. That said I was able to create a bug just fine https://bugzilla.mozilla.org/show_bug.cgi?id=1224140 just make sure to select ARM and Android on platform and OS.
