### ISSUE TITLE
Add 'coming soon' devices

### ISSUE THREAD

**Issue by stripTM** [mozilla/feedthefox#148]
It is frustrating to see that the devices do not appear Mozilla Reference Devices (Flame & Keon), if you are working on incorporating, it is good idea would be informed of it.

**Comment by comzeradd** [comment]
Code-wise there is already the option to add a device without any builds. @ppapadeas @brianking thoughts?

**Comment by ppapadeas** [comment]
We should not add devices without builds without major UI refit, as the expectancy on the /devices/ page is to list devices with builds.

**Comment by comzeradd** [comment]
Ok, so I'm closing this one until we decide (if) we want this and make the necessary UI changes.

**Comment by gaby2300** [comment]
I hope you add the Flame device as soon as possible! Thanks!
