### ISSUE TITLE
Devices page color and font

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/feedthefox#151]
![devices](https://cloud.githubusercontent.com/assets/498592/11117068/71b3ac24-893f-11e5-8ce4-7c5edce72b9c.png)

Device name needs to be clearer. I propose Black text on regular and White text on hover.
@comzeradd ?

**Comment by comzeradd** [comment]
White doesn't look good on this background. I [darken the link](https://github.com/mozilla/feedthefox/pull/161) colors to make them more clear site wide.
