### ISSUE TITLE
New build for Alcatel One Touch

### ISSUE THREAD

**Issue by penserbjorne** [mozilla/feedthefox#167]
Hi guys, I want to add the new build for the Alcatel One Touch Fire aka Hamachi.
And have one question, I compiled from the branch v2.5 but the info displayed by the phone says v2.6, so I decided taken as v2.6, there no problem with the versions?

http://mexmod.com/download_otf.html#v2.6

Regards!

**Comment by brianking** [comment]
@penserbjorne thanks. Please do a little research on what version exactly it is, 2.5 or 2.6. Once we have that information we will consider adding it.

**Comment by penserbjorne** [comment]
Hi, Im sure that I compiled from 2.5 but everybody say that if phone info say 2.6 then is 2.6 :S

**Comment by brianking** [comment]
20151202 Triage - P2.

**Comment by penserbjorne** [comment]
New build from 05/05/2015 , Firefox Sync enabled

**Comment by brianking** [comment]
Since we are removing FxOS features, this is no longer relevant. Reopen if you think it still is.
