### ISSUE TITLE
Missing Sony devices

### ISSUE THREAD

**Issue by lissyx** [mozilla/feedthefox#172]
- Z3 Tablet Compact (scorpion)
- M2 (eagle)
- Z1 (honami)
- Z1 Compact (amami)
- T2 Ultra (tianchi)

Those should be available from: https://github.com/fxpdev/b2g-updates/releases/tag/nightly

**Comment by lissyx** [comment]
@AdFad666 can you help making sure we produce all those? thanks :)

**Comment by stellirin** [comment]
honami and amami are already there!

**Comment by lissyx** [comment]
Then I guess we need FXP to produce scorpion and eagle and then we will be ready to add them on the participation hub :)

**Comment by lissyx** [comment]
Builds are ready for:
- M2 (eagle)
- Z1 (honami)
- Z1 Compact (amami)
- T2 Ultra (tianchi)

Can we add them? @ppapadeas

**Comment by lissyx** [comment]
It should be the same link as other Sony devices

**Comment by lissyx** [comment]
https://github.com/fxpdev/b2g-updates/releases/tag/nightly

**Comment by brianking** [comment]
Builds have been added to the spreadsheet. Please add them @ppapadeas or let me know if I can.

@elioqoshi can we get images for these devices please?

**Comment by elioqoshi** [comment]
On my to-do list. Will do them as soon as I can @brianking

**Comment by elioqoshi** [comment]
These, right?

```
M2 (eagle)
Z1 (honami)
Z1 Compact (amami)
T2 Ultra (tianchi)
```

**Comment by elioqoshi** [comment]
Here are the images. We already have an image of the T2 Ultra online.

Xperia M2
![xperia m2](https://cloud.githubusercontent.com/assets/5436686/11268016/f7211fc6-8eae-11e5-89f9-0956f31f5f5b.png)

Xperia Z1
![xperia z1](https://cloud.githubusercontent.com/assets/5436686/11268029/05a98af6-8eaf-11e5-8ec1-f3e7053b0b6c.png)

Xperia Z1 Compact
![xperia z1 compact](https://cloud.githubusercontent.com/assets/5436686/11268031/0c752282-8eaf-11e5-9dc3-a1c8a23220c9.png)

**Comment by brianking** [comment]
These devices have been added and this issue can now be closed. Thanks all.
