### ISSUE TITLE
Better expose good first bug link as it's not easily found in the list of links.

### ISSUE THREAD

**Issue by yzen** [mozilla/feedthefox#173]
Right now it's only found here:
https://firefoxos.mozilla.community/gaia/
It would be nice to have a more visible shortcut for visitors interested in a tech pathway.

**Comment by brianking** [comment]
20151202 Triage - P1.

**Comment by brianking** [comment]
Since we are removing FxOS features, this is no longer relevant. Reopen if you think it still is.
