### ISSUE TITLE
Determine how to define a section for contributing to Firefox OS accessibility.

### ISSUE THREAD

**Issue by yzen** [mozilla/feedthefox#174]
This could be a good use case for more specific pathway in contributing to Firefox OS. We have (somewhat out of date) this website: http://isfirefoxosaccessibleyet.com/ and also try to list bugs in good first bugs. But, ideally, it would be great to have a UX that is more integrated into the hub.

**Comment by brianking** [comment]
20151202 Triage - P3.

**Comment by brianking** [comment]
Since we are removing FxOS features, this is no longer relevant. Reopen if you think it still is.
