### ISSUE TITLE
Contribute Section should have a page that describes how to get involved in Localization

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla/feedthefox#175]
l10n is one of the areas we really need help with in Firefox OS - there are lots of ways a global community can help spot truncation and display bugs, as well as RTL issues.

**Comment by comzeradd** [comment]
We could have a another flatpage for l10n with some intro text that points to the relevant documentation.

**Comment by brianking** [comment]
This is similar to #174. We should discuss more how to scale up more contribution opportunities before adding more flatpages.

Our focus right now is on technical contributions and l10n is not the perfect fit.

**Comment by brianking** [comment]
20151202 Triage - P3.

**Comment by brianking** [comment]
Since we are removing FxOS features, this is no longer relevant. Reopen if you think it still is.
