### ISSUE TITLE
Xperia Mini should probably be removed

### ISSUE THREAD

**Issue by stellirin** [mozilla/feedthefox#177]
1. It was published over 18 months ago
2. it has this HUGE disclaimer `This in not copiled from source ,it's just a port from Geeksphone Keon so don't ask for fixes because i can't fix them`

A link to an ancient, unmaintained build that wasn't even compiled correctly is probably not something we should promote.

**Comment by ppapadeas** [comment]
@brianking any comments? I kinda agree with @AdFad666

**Comment by brianking** [comment]
Yes agreed, please remove it. I have removed it from the spreadsheet.

**Comment by comzeradd** [comment]
Removed
