### ISSUE TITLE
New mozillians.org not working at login

### ISSUE THREAD

**Issue by brianking** [mozilla/feedthefox#179]
From: https://discourse.mozilla-community.org/t/error-at-connection-with-persona/5337

Hi,

I created an account on https://mozillians.org/fr/ website with persona and I see me connceted. (and I created an account here with the same)

When I try on "Connect" at https://firefoxos.mozilla.community/ I got an error:
"Account Inactive
This account is inactive. Please make sure that you have an acount in mozillians.org."

I don"t understand what I have to activate and where.

**Comment by comzeradd** [comment]
I think only active (vouched) mozillians can login, but I let @akatsoulas confirm. That specific user is not vouched.

**Comment by akatsoulas** [comment]
All Mozillians, vouched and unvouched, should be able to login. Probably, this issue is going to be resolved after the merge and push of pr #164 in production later today. Let's keep this issue open until then to monitor the problem.

**Comment by akatsoulas** [comment]
Fixed via #164
