### ISSUE TITLE
Nice to have: Add selected option visual between Contribute options

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/feedthefox#191]
- this will be a nice thing to have / maybe volunteer task
1. If you go and choose one of the contribute options you will have a menu displayed in your left side.
2. Switching between these options should also show on which you are ( on reps you have it bolded) 
   <img src="https://cloud.githubusercontent.com/assets/1391451/11222257/28f85732-8d72-11e5-95ba-a42491b88624.png" height="250" width="600" />

**Comment by brianking** [comment]
+1

Also, de-linkify the one you are on.

**Comment by brianking** [comment]
20151202 Triage - P2.

**Comment by ioana-chiorean** [comment]
This is not under development anymore. 😢
Will reopen if this will restart! 🍀 ✌🏽
