### ISSUE TITLE
Take down Telegram link from /Connect 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/feedthefox#192]
We should take down Telegram link from the page. @yofiesetiawan revoked the invite link (intentionally) so it won't work properly - will give error etc

@brianking and @williamq - we can say something like "tweet us your id", mail us or if  you think won't fixed spamming we can add only those that will show consistency and work.

https://firefoxos.mozilla.community/connect/

**Comment by comzeradd** [comment]
I removed the link from Connect and Add-ons page.

@brianking you could add some other kind of reference to the Telegram group(s).
