### ISSUE TITLE
Run on sentence in FAQ

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla/feedthefox#193]
https://firefoxos.mozilla.community/foxfooding-faq/

What are my Foxfooding duties if I receive a Mozilla Foxfooding device?
If your application to receive a Mozilla Foxfooding device is approved, then you agree to honour your Foxfooding duties: Foxfood your device at least once a day for 6 months stay up to date with Foxfooding news file bugs when you encounter problems 

I think the above paragraph needs some bullet points as it appears to be a run on sentence.

*Foxfood your device at least once a day for 6 months
*Stay up to date with Foxfooding news
*File new bugs when you encounter problems

**Comment by gaby2300** [comment]
Does someone know when will the foxfooding program will be available for
application?

Many thanks!
Best regards,
Gabriela
QA Mozilla Hispano Team Responsible

**Comment by comzeradd** [comment]
@gaby2300 you should follow the relevant [Discourse category](https://discourse.mozilla-community.org/c/firefox-os-foxfooding) for updates on that.

@brianking what do you think about formatting FAQ text in bulletes to make it more readable?

**Comment by brianking** [comment]
The formatting has now been fixed in that section of the FAQ.

**Comment by brianking** [comment]
@comzeradd yes indeed about formatting, I opened issue #208 for this.
