### ISSUE TITLE
Images for new devices

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/feedthefox#200]
We need images according to specs for the following devices:

Open C
Xperia Z1 Compact (amami)
Xperia Z1 (honami)
Xperia M2 (eagle)
Flame

@elioqoshi can you help?

**Comment by elioqoshi** [comment]
@ppapadeas I already did them, apart the Flame, but here they are again:

Open C
![open c](https://cloud.githubusercontent.com/assets/5436686/11299072/e80500d6-8f83-11e5-8893-00106c64ce97.png)

Xperia Z1 Compact
![xperia z1 compact](https://cloud.githubusercontent.com/assets/5436686/11299076/efa5665a-8f83-11e5-9734-d644e0c29420.png)

Xperia Z1
![xperia z1](https://cloud.githubusercontent.com/assets/5436686/11299080/f76475e8-8f83-11e5-8f9f-b711e1a06ed7.png)

Xperia M2
![xperia m2](https://cloud.githubusercontent.com/assets/5436686/11299085/020419d6-8f84-11e5-8e62-eb4c04c6e854.png)

Flame
![flame](https://cloud.githubusercontent.com/assets/5436686/11299086/088b19f8-8f84-11e5-862c-e8ee71c4c365.png)

They should be good to go :)

**Comment by ppapadeas** [comment]
Thanks Elio! Once again great work!

**Comment by gaby2300** [comment]
@ppapadeas Could you please tell me if  we´ll have dogfooding builds for Flame soon?
