### ISSUE TITLE
Link to Terms and Conditions driects to a 404

### ISSUE THREAD

**Issue by williamq** [mozilla/feedthefox#201]
The link to the Terms and Conditions that appears when you input an IMEI in your profile page is broken.

**Comment by williamq** [comment]
<img width="595" alt="screen shot 2015-11-20 at 15 09 11" src="https://cloud.githubusercontent.com/assets/8026970/11301598/b3271af6-8f98-11e5-9eb0-9963c1eb3aba.png">

**Comment by williamq** [comment]
<img width="1239" alt="screen shot 2015-11-20 at 15 08 51" src="https://cloud.githubusercontent.com/assets/8026970/11301605/ba28eae6-8f98-11e5-8fe8-79fe9358c98b.png">

**Comment by brianking** [comment]
Should link to: https://drive.google.com/file/d/0Bw8tHLgpWV_PbUlZVTlhbFlsU00/view?usp=sharing

**Comment by johngian** [comment]
This should be fixed now after some configuration changes.
