### ISSUE TITLE
Missing Geeksphone Devices

### ISSUE THREAD

**Issue by bobreyes** [mozilla/feedthefox#202]
Saw that the GP Peak is listed under Devices. Would love to see at least the "Revolution" listed therein, too. I think the specs of the Revolution is very close to the Peak (except for the Intel processor).

**Comment by brianking** [comment]
@bobreyes if you know of any builds (2.0 or greater) out in the wild for these devices, please post here.

**Comment by yuniers** [comment]
Yes, I have a Keon and it happened to with 2015-11-14 build http://mexmod.com/download_keon.html#v2.6. I can not mount drives

**Comment by penserbjorne** [comment]
Hi @yuniers , "I can not mount drives" , do you mean SD card in the phone? or when connect to the PC you can not see the devices? Please bring a more exactly description.

**Comment by yuniers** [comment]
@penserbjorne I am referring both cases, when I connect the device to PC and activate the USB Mode, any SD card is not mounted. Too, any photo or music stored on internal SD card is not played.
I have installed Files and since this update only show my external SD card.

**Comment by comzeradd** [comment]
Hi, can you keep the issues just for Hub features and bugs requests? :)

The easiest way to troubleshot a specific image is to either contact the one who build it, or if you think it's a Firefox OS bug you can file it at [Bugzilla](https://bugzilla.mozilla.org/form.fxos.feature?feature_type=existing).

**Comment by bobreyes** [comment]
@brianking B2G 1.3 and 2.0 for the GP Revolution is available via http://downloads.geeksphone.com/

**Comment by brianking** [comment]
20151202 Triage - P2.

**Comment by brianking** [comment]
Since we are removing FxOS features, this is no longer relevant. Reopen if you think it still is.
