### ISSUE TITLE
[URGENT] Update Nexus 4 and 5 Builds

### ISSUE THREAD

**Issue by brianking** [mozilla/feedthefox#203]
Brian, William, Pierros,

Please update the Hub on the Green "nightly" download button) for Nexus 4 & 5 back to the original links indicated below.  The reasoning is that we have resolve the issue on FxOS side but would now require a change back to the original links.  Since it quite late for Pierros now.  Can either Brian or William do this change instead?  After this is done.  We are good with the Nexus 4 & 5 builds on the Hub!!

Brian, William
Let me know when either one of you have completed this change on the website.

Nexus 4

```
https://index.taskcluster.net/v1/task/gecko.v1.mozilla-central.latest.linux.nexus-4-kk-user.opt/artifacts/public/build/nexus-4-kk.zip
```

Nexus 5

```
https://index.taskcluster.net/v1/task/gecko.v1.mozilla-central.latest.linux.nexus-5-user.opt/artifacts/public/build/nexus-5-l.zip
```

Thanks,
Jean

cc @ppapadeas @williamq

**Comment by comzeradd** [comment]
I did the url changes
