### ISSUE TITLE
Images on homepage are not retina

### ISSUE THREAD

**Issue by tofumatt** [mozilla/feedthefox#212]
On my retina 13" MacBook Pro, all the images are fuzzy and sad-making as they aren't 2x.

**Comment by comzeradd** [comment]
I don't have a Macbook to test it, but we could probably change all graphics to svg.

**Comment by tofumatt** [comment]
That or just double the pixel density and set the image size in CSS/HTML.

If you want me to test it just send me a link or something, happy to help :-)

**Comment by brianking** [comment]
Since we are removing FxOS features, this is no longer relevant. Reopen if you think it still is.

Image are going away on homepage mostly, see issue #218.
