### ISSUE TITLE
LG FX0 with b2g 2.1.0.0-prerelease

### ISSUE THREAD

**Issue by caos30** [mozilla/feedthefox#213]
Hi, i've a LG FX0 with b2g 2.1.0.0-prerelease. I bought the device on Amazon USA this month, so it's the "international unlocked version". The original LG FX0 (sold in Japan and build for au Japan) had the 2.0, but my phone say: 2.1.

I really don't know nothing about ROMS, but in the form of the section "devices" of this project doesn't appear the "LG FX0". I signed up today as user in this project, so i don't understand very well why do you need my device model... Maybe for give you a copy of my system for be useful for other users or maybe for build a 2.5 version for the same device?

Please, someone can explain a little more in a "low technical level" which is the purpose of this list of devices? 

Thanks in advance, and you're very welcome if you need help or collaboration :)
Sergi

**Comment by brianking** [comment]
Since we are removing FxOS features, this is no longer relevant. Reopen if you think it still is.

**Comment by caos30** [comment]
Please, what do you mean when say "removing FxOS features"? removing it from WHERE?
Indeed, do you know something about the 2.6 stable version? I installed the 2.6 beta version some months ago, even i wrote a popular guide for it ;)

https://www.reddit.com/r/fx0/comments/430x8q/how_to_install_firefox_os_26_en_lg_fx0

Thanks for any helpful info ;)
Cheers!
