### ISSUE TITLE
Home Page Re-Branding to CD

### ISSUE THREAD

**Issue by brianking** [mozilla/feedthefox#218]
As we will not a CD logo, the proposal here is:
- Replace logo on top left with generic Mozilla Name
- Replace large ‘Firefox OS’ (it is an SVG image) text with ‘Connected Devices’
- Remove large phone image. Replace with alternative, or remove and make heading smaller

@ppapadeas I hear you have an alternative proposal, please share.

**Comment by MarciaZikan** [comment]
@ppapadeas any updates?

**Comment by MarciaZikan** [comment]
@ppapadeas  Please, add this new copy about Connected Devices:

 Welcome to the Connected Devices Participation Hub, your starting point to get involved in Connected Devices, both through our Product Innovation Process and our Community Experimentation Launchpad.
Join a vibrant open source community and make Connected Devices a platform for innovation that will unlock the power of the web.

Find out ways to get involved and stay tuned for more information soon !

**Comment by MarciaZikan** [comment]
@ any update on this?

**Comment by comzeradd** [comment]
Do we have any graphics related to Connected Devices we could use instead of the Firefox OS phone screenshot?

**Comment by MarciaZikan** [comment]
@comzeradd No, we have nothing so far.

**Comment by brianking** [comment]
P1 - 20160517

And we are not going to have any CD branding in the near to mid-term. See comment 0 for suggested changes.
