### ISSUE TITLE
Firefox OS Participation Hub URL change to CD

### ISSUE THREAD

**Issue by MarciaZikan** [mozilla/feedthefox#221]
Replace the current URL firefoxos.mozilla.community to cd.mozilla.community

**Comment by MarciaZikan** [comment]
@ppapadeas Pierros, I opened this new issue but I don't have permissions to add the label and Assignee. Do you know why?
Thanks, Marcia.

**Comment by MarciaZikan** [comment]
@ppapadeas any updates on this?

**Comment by brianking** [comment]
P1 - 20160517
