### ISSUE TITLE
remove all references to Firefox OS on the new CD Participation Hub

### ISSUE THREAD

**Issue by MarciaZikan** [mozilla/feedthefox#222]
@ppapadeas Please, remove all references to Firefox OS on the new CD Participation Hub

**Comment by brianking** [comment]
Possible dupe of #219 or this is broader in scope.

**Comment by comzeradd** [comment]
Do we just replace Firefox OS with Connected Devices or do we need to make any adjumests on the text? I'm mostly talking about the About text on the frontpage.

**Comment by MarciaZikan** [comment]
@comzeradd Please, add this new copy About Connected Devices on the frontpage:

Welcome to the Connected Devices Participation Hub, your starting point to get involved in Connected Devices, both through our Product Innovation Process and our Community Experimentation Launchpad.
Join a vibrant open source community and make Connected Devices a platform for innovation that will unlock the power of the web.

Find out ways to get involved and stay tuned for more information soon !

**Comment by brianking** [comment]
P1 - 20160517
