### ISSUE TITLE
Remove need to agree to Terms and Conditions on the new CD Participation Hub

### ISSUE THREAD

**Issue by MarciaZikan** [mozilla/feedthefox#223]
@ppapadeas Please, Remove need to agree to Terms and Conditions on the new CD Participation Hub

**Comment by MarciaZikan** [comment]
@ppapadeas any updates on this?

**Comment by comzeradd** [comment]
We have a couple of places where we ask user consent. Are you talking about the TOS text when adding a device with IMEI?

**Comment by MarciaZikan** [comment]
@comzeradd Yes

**Comment by comzeradd** [comment]
That TOS is a legal bound, since we ask for IMEI numbers. If we remove this we should also stop asking IMEIs.

**Comment by MarciaZikan** [comment]
@comzeradd 
Sure, let's stop asking IMEIs as well.

**Comment by brianking** [comment]
P1 - 20160517
