### ISSUE TITLE
Replace Persona with an alternative login solution on https://firefoxos.mozilla.community/

### ISSUE THREAD

**Issue by rfk** [mozilla/feedthefox#226]
Persona will be decommissioned by the end of 2016, and I'm trying to ensure that all the work we need to do between now and then is captured under the following meta-bug:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1197381

I couldn't find an existing bug for migrating https://firefoxos.mozilla.community/ away from Persona, so I'm creating one.  If there is an existing bug, please point me to it so I can include it in the meta bug tree.

Also, does this project have a corresponding bugzilla component?  Having this filed in bugzilla would make my job of wrangling all these migrations much easier :-)

**Comment by comzeradd** [comment]
Hey @rfk. At the moment this project doesn't have a Bugzilla component. We track the work here on issues.

**Comment by rfk** [comment]
No worries, thanks for clarifying.  Also, I realized that I should have linked to this page with more information, context and suggestions:

  https://mana.mozilla.org/wiki/display/Identity/Persona+migration+guide+for+internal+sites

**Comment by rfk** [comment]
Hi, just checking in as we get closer to the planned shutdown date - is there any update on moving this project away from Persona logins?

**Comment by comzeradd** [comment]
This website will be [decommissioned](https://github.com/mozilla/feedthefox/issues/229) in the next few days, so no need to deal with Persona EOL here.

**Comment by brianking** [comment]
The Site is still live.
