### ISSUE TITLE
Turn Off The Site

### ISSUE THREAD

**Issue by brianking** [mozilla/feedthefox#229]
We have been unsuccessful in finding a compelling use case to keep it alive for CD.

I posted on dev-fxos a few weeks ago to see if the community wanted to take it over. There was no reply.

The next step is to take the site down.

**Comment by brianking** [comment]
I wonder if we should redirect to https://wiki.mozilla.org/B2G_OS ?

**Comment by johngian** [comment]
Project instance is decommissioned. URLs redirect to the wiki page.
