### ISSUE TITLE
Scale access to contribution areas on hompage

### ISSUE THREAD

**Issue by brianking** [mozilla/feedthefox#25]
In the current test version, the homepage only lists two contribution areas on the right in the main body. I'm wondering how this will scale as we have more, such as add-ons and gaia dev.
<img width="481" alt="hub1" src="https://cloud.githubusercontent.com/assets/114116/10754445/e9b0f61e-7c97-11e5-8174-2143362f2c94.png">

Related, I believed we discussed access to these pages via the top navigation, but am not seeing anything there currently.

**Comment by comzeradd** [comment]
Not all option fit on the top navbar. We could have a 'Contribute' option that leads to a contribute page with all available options.

**Comment by brianking** [comment]
Or could 'Contribute' be a drop down? That wouldn't solve the section on the home page though. In fact that section is not in the copy document, so we can probably get rid of it.

**Comment by comzeradd** [comment]
This is now fixed after #56. The navbar still needs some work, but all pages are now available through a dropdown menu.
