### ISSUE TITLE
Logo / Title Spacing Issues

### ISSUE THREAD

**Issue by brianking** [mozilla/feedthefox#66]
Feedback from @geroter :

The logo and spacing with Contribution Hub doesn’t look quite right. Maybe create a logo mark using the Firefox OS- Participation type of logo for the site (Firefox OS on one line, next line underneath “Participation Hub”)

**Comment by brianking** [comment]
We also have: https://pbs.twimg.com/profile_images/658964541418541056/npXuIZsH_400x400.png if something like that is needed.

**Comment by ppapadeas** [comment]
Let's go with two line option. @comzeradd it will be logo and next to it (spaced evenly on height) line1: "Firefox OS" line2: "Participation Hub"

**Comment by comzeradd** [comment]
What about the home page? We already have the "Firefox OS" wordmark as part of the CTA.
