### ISSUE TITLE
Change Call to Action

### ISSUE THREAD

**Issue by brianking** [mozilla/feedthefox#67]
The call to action shouldn’t be “Hack it on your device” but instead “Install it on your device” or “Get it on your device”.

**Comment by ppapadeas** [comment]
How about "Get it for your device" ?

**Comment by brianking** [comment]
- @geroter 

OK with me. I suspect George just wants to avoid the word Hack.

**Comment by ppapadeas** [comment]
Ok we are going for "Get it for your device" 

@comzeradd please proceed.
