### ISSUE TITLE
Text For Devices Page

### ISSUE THREAD

**Issue by brianking** [mozilla/feedthefox#71]
Suggestions by @geroter :

Search for your device and instructions on how to replace its existing operating system with Firefox OS.

... And under “Don’t see your device here?” button, I suggest having the following text with a hyperlink:

Not ready to replace your operating system. Click here to try out Firefox OS as an Android app.

**Comment by comzeradd** [comment]
So the “Don’t see your device here?” all three current options? Just B2GDroid?

**Comment by brianking** [comment]
Replace all three with what is described above.

**Comment by brianking** [comment]
20151202 Triage - P1.

**Comment by brianking** [comment]
Since we are removing devices functionality, this is no longer relevant. Reopen if you think it still is.
