### ISSUE TITLE
Text for Dashboard Page

### ISSUE THREAD

**Issue by brianking** [mozilla/feedthefox#72]
From @geroter ....

definitely need explanation text at the top. My suggestion:

Help make Firefox OS better. Contribute to prioritizing features or defects by voting for those you most want to see worked on. Report a feature or defect by clicking the ‘+’ button on the right.

**Comment by ppapadeas** [comment]
Let's have this text in a tooltip hover over a "i" icon next to Dashboard title.

@comzeradd please proceed.

**Comment by ppapadeas** [comment]
Tooltip is not acceptable from @brianking we should add it as a proper text on top.

@comzeradd please fix.

**Comment by comzeradd** [comment]
Do we want this to be on the same format as the rest of the flatpages? If yes any ideas on the graphic on the left?
