### ISSUE TITLE
Add Images to Foxfooding Pages

### ISSUE THREAD

**Issue by brianking** [mozilla/feedthefox#73]
About and FAQ should have images, similar to the other flat pages.

**Comment by comzeradd** [comment]
Do we have any graphics for Foxfooding in general?

**Comment by elioqoshi** [comment]
After @ppapadeas asked me, I created these proposals:

![photo_2015-11-05_16-27-23](https://cloud.githubusercontent.com/assets/5436686/10972580/2151d73e-83da-11e5-85ff-9d635e0f00e6.jpg)
![photo_2015-11-05_16-27-28](https://cloud.githubusercontent.com/assets/5436686/10972581/2154d18c-83da-11e5-97a3-a331f751a2a9.jpg)

**Comment by ppapadeas** [comment]
@comzeradd put the logo by @elioqoshi  (only the crest to start with). In the meantime @brianking look (or take during Mozfest) pictures with people foxfooding.

**Comment by comzeradd** [comment]
@elioqoshi do you have the second one in a good resolution (preferably vector). I have the original pdf but this specific one seems to be missing.

**Comment by elioqoshi** [comment]
@comzeradd here we go!
https://dl.dropboxusercontent.com/u/62482708/v2.pdf
