### ISSUE TITLE
Instructions for Flashing

### ISSUE THREAD

**Issue by brianking** [mozilla/feedthefox#76]
@ppapadeas what is your plan for that?

We might have special requirements for Nexus builds. Should we create a flat page for that?

**Comment by comzeradd** [comment]
Don't we plan on having all device documentation on MDN?

**Comment by ppapadeas** [comment]
Every device we have should include a documentation link to MDN or other documentation site.

**Comment by brianking** [comment]
What link did you use?

Here are the Nexus build instructions, and they may be different that the generic instructions on MDN and we might need them somewhere inline on the Hub.

Step 1: Download the zip file. e.g: nexus-4-kk.zip
Step 2: unzip the file, ensure flash.sh or flash.bat (for Windows) is available under b2g-distro folder.
Step 3: Open terminal and direct to the path where the unzip folder located, e.g: cd nexus-4-kk/b2g-distro
Step 4: Type in adb devices to ensure device is found. (link to Android Debug Bridge - adb command setup if command not available)
Step 5: Type in ./flash.sh or flash.bat to execute the installation.
Profit!

**Comment by nhirata** [comment]
Windows batch file ( flash.bat) doesn't exist yet : https://bugzilla.mozilla.org/show_bug.cgi?id=1221537

**Comment by pdolanjski** [comment]
While we wait for the windows script, let's put in the following instructions:
Nexus 4/5 instructions:

Before starting, make you have followed the instructions found here to get ADB/fastboot up and running: https://developer.mozilla.org/en-US/Firefox_OS/Debugging/Installing_ADB

Note: Windows flash script is not yet available - it is coming soon!

For non-Windows users:
Step 1: Download the zip file. e.g: nexus-4-kk.zip
Step 2: unzip the file, ensure flash.sh is available under b2g-distro folder.
Step 3: Open terminal and direct to the path where the unzip folder located, e.g: cd nexus-4-kk/b2g-distro
Step 4: Type in adb devices to ensure device is found. (link to Android Debug Bridge, http://developer.android.com/tools/help/adb.html - adb command setup if command not available)
Step 5: Type in ./flash.sh to execute the installation.

**Comment by pdolanjski** [comment]
We're using MDN now, so ignore this.
