### ISSUE TITLE
Community / Social Page

### ISSUE THREAD

**Issue by brianking** [mozilla/feedthefox#77]
Need to create the flat page - @brianking

@ppapadeas Can we fit this in the nav bar? If not, any suggestions?

**Comment by brianking** [comment]
Copy so far .. will seek review and extra copy + pictures:

By contributing to Firefox OS, you are joining a global community. It is a community deeply committed to Mozilla’s mission, to the open web, and to having a smartphone and IoT platform to use, tinker with, and develop for.

Join our social channels to keep up with the latest updates:
- Twitter 
- Facebook
- Instagram

The hashtag for social posts is #foxfooding. Have fun with it. Post pictures of your customized home screen. Use it at Firefox OS events where you are hacking on something. Do an unboxing of you shiny new foxfooding device!

**Comment by brianking** [comment]
Suggestion from Liz Hull:

By contributing to Firefox OS, you are joining a global community. It is a community deeply committed to Mozilla’s mission, to the open web, and to having a smartphone and IoT platform to use, tinker with, and develop for.

Follow our participation social channels to keep up with the latest updates:
- Twitter
- Facebook
- Instagram

Have fun with it! Post pictures of your customized home screen, use it at Firefox OS events, or do an unboxing of your shiny new foxfooding device, all with the #foxfooding hashtag.

**Comment by ppapadeas** [comment]
@brianking add it as a flat page. Once you do it link it here.

**Comment by comzeradd** [comment]
Do we want this to be on the same format as the rest of the flatpages? If yes any ideas on the graphic on the left?

**Comment by brianking** [comment]
My idea was for it to be a screen snippet of the Firefox OS Participate
Facebook page.

**Comment by comzeradd** [comment]
The problem mentioned at #97 is now fixed and the page is live.
