### ISSUE TITLE
Foxfooding interest in profile

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/feedthefox#78]
We need a checkbox (with AJAX submit) under the foxfooding section of the profile that has the text: 

"Check this box if you're interested in participating in the Foxfooding program and want to get notified by email once a foxfooding build is available for your device"

This should be stored in the profile model as a boolean.

**Comment by comzeradd** [comment]
@ppapadeas Is this different from what we already have (not ajaxified at the moment) or is this just a change on wording? 

https://github.com/mozilla/feedthefox/blob/master/feedthefox/base/templates/jinja2/profile.html#L74-L77

**Comment by ppapadeas** [comment]
It is a different field. The one is on privacy (existing) the other one (on this issue) is on Foxfooding.

**Comment by ppapadeas** [comment]
Also this is off by default. (the privacy one is ON)

**Comment by johngian** [comment]
Fixed after #112
