### ISSUE TITLE
Fix Contribute Section on Homepage

### ISSUE THREAD

**Issue by brianking** [mozilla/feedthefox#80]
Right now it only shows 2 contribution areas, and probably won't scale to fit more.

Possible solution. Create an index page that links to all contribution pages. And then in that section, add a 'More...' link that goes to the index page.

Any other possible solutions @willliamq?

**Comment by williamq** [comment]
+1 on the idea of adding a link to  "More contribution opportunities...." at the bottom (under B2Gdroid section)

**Comment by pdolanjski** [comment]
Should we change B2GDroid naming in that drop down too?

**Comment by comzeradd** [comment]
@williamq @brianking should we update all mentions to B2GDroid to Developer Preview? This is mostly for the Contribute menu and the button on the home page.

**Comment by brianking** [comment]
@comzeradd Yes please, and depending on what fits it should be, in order of preference:
- Firefox OS 2.5 Developer Preview For Android
- Developer Preview For Anrdoid

It really needs to mention Android because it has to differentiate from the main Firefox OS experience. I know this is tough is some places.
