### ISSUE TITLE
Add imei validator

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/feedthefox#81]

**Comment by ppapadeas** [comment]
http://www.dotnetspider.com/resources/29819-Javascript-For-IMEI-Validation.aspx

That might be the best way for validation. btw, IMEI is using Luhn.

**Comment by ppapadeas** [comment]
That might be a nice option too: https://gist.github.com/ShirtlessKirk/2134376

**Comment by akatsoulas** [comment]
PR #108 opened. The IMEI can be validated with the Luhn algorithm.

Quick intro:
https://en.wikipedia.org/wiki/Luhn_algorithm

**Comment by akatsoulas** [comment]
This is now merged
