### ISSUE TITLE
Copy Edit: Consistent punctuation in lists

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/feedthefox#95]
Edit to: 
- Setup your development environment for making ports
- Help with a port that’s already in-progress or start a new one.
- Visit the Devices section here on the Hub to find a compatible device and download a build to flash to your device

Problem: Inconsistent punctuation 
Solution: remove all punctuation from this list (grammatically incorrect to punctuate this sort of list and it looks sloppy)

**Comment by ppapadeas** [comment]
Fixed!
