### ISSUE TITLE
Legal Text for Hub

### ISSUE THREAD

**Issue by brianking** [mozilla/feedthefox#98]
1. When downloading a build
2. When adding a device

We need the final text for both of these.

**Comment by brianking** [comment]
Email sent to Elvin looking for final text.

**Comment by brianking** [comment]
Text received. Here is the PDF version we will link to from the opt-in that will list the basic requirements:

https://drive.google.com/file/d/0Bw8tHLgpWV_PbUlZVTlhbFlsU00/view?usp=sharing

**Comment by comzeradd** [comment]
This is now merged.
